services:
  postgres:
    image: postgres:14
    container_name: entrevista_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: entrevista
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../storage/database:/var/lib/postgresql/data
